"""Generate a minimal ``.app`` wrapper to solve the macOS microphone-permission problem.

macOS TCC grants microphone access to a *stable identity*. A bare CLI launched
from a terminal inherits the terminal's permission (fragile), and a launchd
process often can't raise the prompt at all. An ``.app`` bundle has its own
bundle identifier and code signature, so macOS shows the prompt once and
remembers the grant. The bundle declares ``NSMicrophoneUsageDescription`` (a
hard requirement — accessing the mic without it crashes) and simply execs the
hey-claude listener.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from .config import log_path
from .service import _path_env, _program_args

BUNDLE_ID = "com.heyclaude.listener"


def default_dest() -> Path:
    return Path.home() / "Applications" / "Hey Claude.app"


def _info_plist() -> str:
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>Hey Claude</string>
    <key>CFBundleDisplayName</key>     <string>Hey Claude</string>
    <key>CFBundleIdentifier</key>      <string>{BUNDLE_ID}</string>
    <key>CFBundleVersion</key>         <string>1.0</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>CFBundleExecutable</key>      <string>hey-claude</string>
    <key>LSMinimumSystemVersion</key>  <string>12.0</string>
    <key>LSUIElement</key>             <true/>
    <key>NSMicrophoneUsageDescription</key>
    <string>Hey Claude listens for the wake word to dispatch a Claude Code agent.</string>
</dict>
</plist>
"""


def _launcher_script() -> str:
    args = " ".join(_shq(a) for a in _program_args())
    log = log_path()
    return f"""#!/bin/bash
# Auto-generated by `hey-claude app`. Execs the listener with a sane PATH and
# logs to the standard location so the menu-bar-less app has visible output.
export PATH="{_path_env()}"
export HOME="{Path.home()}"
mkdir -p "{log.parent}"
exec {args} >> "{log}" 2>&1
"""


def _shq(s: str) -> str:
    return "'" + s.replace("'", "'\\''") + "'"


def build(dest: Path | None = None, *, sign: bool = True) -> Path:
    app = (dest or default_dest()).expanduser()
    macos = app / "Contents" / "MacOS"
    macos.mkdir(parents=True, exist_ok=True)

    (app / "Contents" / "Info.plist").write_text(_info_plist(), encoding="utf-8")
    exe = macos / "hey-claude"
    exe.write_text(_launcher_script(), encoding="utf-8")
    exe.chmod(0o755)

    if sign:
        # Ad-hoc signature gives the bundle a stable identity for TCC.
        try:
            subprocess.run(
                ["codesign", "--force", "--sign", "-", str(app)],
                capture_output=True, text=True, timeout=30,
            )
        except (OSError, subprocess.SubprocessError):
            pass
    return app


def build_and_report(dest: Path | None = None) -> int:
    try:
        app = build(dest)
    except OSError as exc:
        print(f"✗ failed to build app: {exc}", file=sys.stderr)
        return 1
    print(f"✓ built {app}")
    print("\nNext:")
    print(f'  open "{app}"        # launches it; macOS will prompt for mic access — click Allow')
    print("  then add it to Login Items (System Settings → General → Login Items) to start at login.")
    print(f"\nLogs: {log_path()}")
    return 0
