#!/usr/bin/env python3
"""Generate hey-claude's bundled *soundpacks* — themed sets of the five event
cues (wake / endpoint / dispatch / cancel / error) the listener plays.

Why packs: the listen loop fires the same handful of cues constantly, so the
"voice" of the tool is mostly these five sounds. A pack lets you reskin all of
them at once (``hey-claude sounds pack arcade``) and — because an event can hold
several variant files — the wake cue *rotates* so it never feels robotic.

All audio here is **synthesized from scratch** (sine / square / swept partials
under shaped envelopes). Nothing is sampled or ripped: these ship in a public
package, so they have to be original. To use copyrighted/meme audio (StarCraft
barks, etc.), a user drops their own files into a custom pack folder — see the
``sounds`` help. Re-run to regenerate every bundled pack:

    python scripts/gen_soundpacks.py

Output: src/hey_claude/soundpacks/<pack>/<event>[-<n>].wav  (44.1 kHz, 16-bit
mono). The ``studio`` pack is the default and lives in ../earcons (generated by
gen_earcons.py), so it is intentionally *not* re-emitted here.
"""

from __future__ import annotations

import struct
import wave
from pathlib import Path

import numpy as np

SR = 44100
OUT = Path(__file__).resolve().parent.parent / "src" / "hey_claude" / "soundpacks"

# ---------------------------------------------------------------------------
# Synthesis primitives
# ---------------------------------------------------------------------------


def _env(n, *, attack=0.005, decay_frac=0.32):
    """Fast-attack / exponential-decay amplitude envelope of length ``n``."""
    t = np.linspace(0, 1, n, endpoint=False)
    e = np.exp(-t / decay_frac)
    a = max(1, int(SR * attack))
    e[:a] *= np.linspace(0, 1, a)
    return e


def sine(freq, dur, *, amp=1.0, partials=(1.0, 0.22, 0.08), attack=0.005,
         decay_frac=0.32, bell=False):
    n = int(SR * dur)
    t = np.linspace(0, dur, n, endpoint=False)
    sig = np.zeros(n)
    for i, pa in enumerate(partials, start=1):
        sig += pa * np.sin(2 * np.pi * freq * i * t)
    if bell:
        for mult, pa in ((2.76, 0.10), (5.40, 0.04)):
            sig += pa * np.sin(2 * np.pi * freq * mult * t) * np.exp(-t / (dur * 0.25))
    return amp * sig * _env(n, attack=attack, decay_frac=decay_frac)


def square(freq, dur, *, amp=1.0, duty=0.5, attack=0.003, decay_frac=0.5,
           detune=0.0):
    """Pulse-wave note — the chiptune voice. ``detune`` (Hz) thickens it."""
    n = int(SR * dur)
    t = np.linspace(0, dur, n, endpoint=False)
    phase = (freq * t) % 1.0
    sig = np.where(phase < duty, 1.0, -1.0)
    if detune:
        ph2 = ((freq + detune) * t) % 1.0
        sig = 0.6 * sig + 0.4 * np.where(ph2 < duty, 1.0, -1.0)
    return amp * sig * _env(n, attack=attack, decay_frac=decay_frac)


def sweep(f0, f1, dur, *, amp=1.0, wave="sine", attack=0.003, decay_frac=0.5):
    """Glide from ``f0`` to ``f1`` over ``dur`` — sci-fi zaps and UI swooshes."""
    n = int(SR * dur)
    t = np.linspace(0, dur, n, endpoint=False)
    inst = np.linspace(f0, f1, n)
    phase = 2 * np.pi * np.cumsum(inst) / SR
    sig = np.sin(phase) if wave == "sine" else np.sign(np.sin(phase))
    return amp * sig * _env(n, attack=attack, decay_frac=decay_frac)


def mix(*layers):
    length = max(int(off * SR) + len(s) for off, s in layers)
    buf = np.zeros(length)
    for off, s in layers:
        i = int(off * SR)
        buf[i:i + len(s)] += s
    return buf


def normalize(buf, peak=0.32):
    m = np.max(np.abs(buf)) or 1.0
    buf = buf / m * peak
    f = max(1, int(0.004 * SR))  # click-free tail
    buf[-f:] *= np.linspace(1, 0, f)
    return buf


def write(pack, name, buf):
    d = OUT / pack
    d.mkdir(parents=True, exist_ok=True)
    data = (np.clip(buf, -1, 1) * 32767).astype("<i2")
    with wave.open(str(d / f"{name}.wav"), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(b"".join(struct.pack("<h", int(s)) for s in data))


# Pitches (Hz)
C5, D5, E5, G5, A5, B5 = 523.25, 587.33, 659.25, 783.99, 880.00, 987.77
C6, D6, E6, G6, A6 = 1046.50, 1174.66, 1318.51, 1567.98, 1760.00
G4, A4 = 392.00, 440.00
A3, F3, E3, D3, C3 = 220.00, 174.61, 164.81, 146.83, 130.81


# ---------------------------------------------------------------------------
# Packs — each returns {event: [buffer, ...]}.  Multiple buffers for an event
# become rotating variants (wake.wav, wake-2.wav, …).
# ---------------------------------------------------------------------------


def pack_arcade():
    """8-bit chiptune — retro RTS / arcade-cabinet energy."""
    sq = lambda f, d, **k: square(f, d, decay_frac=0.6, **k)
    return {
        "wake": [
            mix((0.00, sq(C5, 0.07)), (0.07, sq(E5, 0.07)), (0.14, sq(G5, 0.10))),
            mix((0.00, sq(G5, 0.07)), (0.08, sq(C6, 0.12))),  # variant: rising 4th
        ],
        "endpoint": [mix((0.0, sq(E5, 0.08, duty=0.25)))],
        "dispatch": [mix(  # "power-up" run
            (0.00, sq(C5, 0.05)), (0.05, sq(E5, 0.05)), (0.10, sq(G5, 0.05)),
            (0.15, sq(C6, 0.05)), (0.20, sq(E6, 0.14)),
        )],
        "cancel": [mix((0.00, sq(E5, 0.07)), (0.09, sq(C5, 0.12, duty=0.25)))],
        "error": [mix(
            (0.00, sq(A3, 0.12, duty=0.5, detune=6.0)),
            (0.14, sq(F3, 0.18, duty=0.5, detune=6.0)),
        )],
    }


def pack_zen():
    """Soft singing bowls & marimba — mellow, warm, unhurried."""
    bowl = lambda f, d, **k: sine(f, d, partials=(1.0, 0.5, 0.25, 0.12),
                                  decay_frac=0.4, bell=True, **k)
    return {
        "wake": [
            mix((0.00, bowl(A4, 0.5)), (0.12, bowl(E5, 0.6))),
            mix((0.00, bowl(G4, 0.5)), (0.14, bowl(D5, 0.6))),  # variant
        ],
        "endpoint": [mix((0.0, bowl(D5, 0.45)))],
        "dispatch": [mix(  # pentatonic ascent
            (0.00, bowl(C5, 0.5)), (0.14, bowl(E5, 0.5)), (0.28, bowl(G5, 0.7)),
        )],
        "cancel": [mix((0.00, bowl(E5, 0.4)), (0.16, bowl(A4, 0.55)))],
        "error": [mix((0.00, bowl(A3, 0.5)), (0.20, bowl(F3, 0.7)))],
    }


def pack_starship():
    """Sci-fi console bleeps — clipped FM-ish blips and quick freq sweeps."""
    blip = lambda f, d, **k: sine(f, d, partials=(1.0, 0.0, 0.35, 0.0, 0.15),
                                 **{"decay_frac": 0.5, **k})
    return {
        "wake": [
            mix((0.00, sweep(500, 1200, 0.12)), (0.10, blip(A6, 0.12))),
            mix((0.00, blip(G5, 0.06)), (0.07, blip(D6, 0.06)), (0.14, blip(A6, 0.12))),
        ],
        "endpoint": [mix((0.0, blip(E6, 0.10, decay_frac=0.35)))],
        "dispatch": [mix(  # "comms confirmed"
            (0.00, blip(C6, 0.12)), (0.10, blip(G6, 0.12)),
            (0.20, sine(C6 * 2, 0.30, partials=(1.0, 0.2), decay_frac=0.3, bell=True)),
        )],
        "cancel": [mix((0.0, sweep(900, 380, 0.22)))],
        "error": [mix(  # dissonant low warble
            (0.00, sine(E3, 0.22, partials=(1.0, 0.4, 0.2), decay_frac=0.5)),
            (0.00, sine(E3 * 1.06, 0.22, partials=(1.0, 0.4), decay_frac=0.5, amp=0.7)),
            (0.18, sine(C3, 0.30, partials=(1.0, 0.4, 0.2), decay_frac=0.5)),
        )],
    }


def pack_pulse():
    """Minimal UI ticks — tiny, soft, modern; stays out of the way."""
    tick = lambda f, d=0.05, **k: sine(f, d, attack=0.001,
                                      **{"partials": (1.0, 0.3), "decay_frac": 0.18, **k})
    return {
        "wake": [
            mix((0.00, tick(A6, 0.045)), (0.06, tick(E6, 0.06))),
            mix((0.00, tick(E6, 0.045)), (0.06, tick(A6, 0.06))),
        ],
        "endpoint": [mix((0.0, tick(D6, 0.05)))],
        "dispatch": [mix((0.00, tick(E6, 0.05)), (0.07, tick(A6, 0.08)))],
        "cancel": [mix((0.00, tick(A5, 0.05)), (0.07, tick(E5, 0.07)))],
        "error": [mix((0.00, tick(A3, 0.10, partials=(1.0, 0.5))),
                      (0.12, tick(F3, 0.14, partials=(1.0, 0.5))))],
    }


PACKS = {
    "arcade": (pack_arcade, 0.30),
    "zen": (pack_zen, 0.26),
    "starship": (pack_starship, 0.30),
    "pulse": (pack_pulse, 0.24),
}


def build():
    for pack, (fn, peak) in PACKS.items():
        events = fn()
        count = 0
        for event, variants in events.items():
            for i, buf in enumerate(variants):
                name = event if i == 0 else f"{event}-{i + 1}"
                write(pack, name, normalize(buf, peak=peak))
                count += 1
        print(f"  {pack:<9} {count} files")


if __name__ == "__main__":
    print(f"Generating soundpacks → {OUT}")
    build()
    print("done.")
